routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

// Ajax Routes...
Route::prefix('ajax')->group(function () {
    Route::post('/delete-image', 'Admin\AnimalsController@deleteImage')->middleware('auth');
    Route::post('/sort-images', 'Admin\AnimalsController@sortImages')->middleware('auth');
});

// Animal Routes...
Route::prefix('animals')->group(function () {
    Route::get('/view/{id}', 'AnimalController@getAnimal');
    Route::get('/{filter?}', 'AnimalController@getListings');
});

// Authentication Routes...
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => '', 'uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

// Password Reset Routes...
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/reset', ['as' => '', 'uses' => 'Auth\ResetPasswordController@reset']);
Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

// Admin Routes
Route::prefix('admin')->middleware('auth')->namespace('Admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    // Animals
    Route::prefix('animals')->group(function () {
        Route::get('/', 'AnimalsController@index')->name('admin.animals.index');
        Route::get('/{id}', 'AnimalsController@getUpdate')->name('admin.animals.update');
        Route::post('/{id}', 'AnimalsController@postUpdate');
        Route::get('/images/{id}', 'AnimalsController@getImages')->name('admin.animals.images');
        Route::post('/images/{id}', 'AnimalsController@postImages');
    });

    // Caresheets
    Route::prefix('caresheets')->group(function () {
        Route::get('/', 'CaresheetController@index')->name('admin.caresheets.index');
    });

    // Blog
    Route::prefix('blog')->group(function () {
        Route::get('/', 'BlogController@index')->name('admin.blog.index');
        Route::get('/{id}', 'BlogController@getUpdate')->name('admin.blog.update');
        Route::post('/{id}', 'BlogController@postUpdate');
    });

    // Season
    Route::prefix('season')->group(function () {
        Route::get('/', 'SeasonController@index')->name('admin.season.index');
    });

    // Merchandise
    Route::prefix('merch')->group(function () {
        Route::get('/', 'MerchController@index')->name('admin.merch.index');
    });
});

// Blog Routes
Route::prefix('blog')->group(function () {
    Route::get('/', 'BlogController@index')->name('blog.index');
});

// Caresheet Routes
Route::prefix('caresheets')->group(function () {
    Route::get('/', 'CaresheetController@index')->name('caresheets.index');
});

// Single Pages
Route::get('season', 'HomeController@season')->name('season');

app/Models/Animal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'item_number', 'title', 'description', 'categories', 'species', 'dob', 'price', 'gender', 'sold_to', 'sold_at',
        'sold_for', 'tracking_number', 'notes'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany(Image::class)->orderBy('order','asc');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function featuredImage()
    {
        return $this->hasOne(Image::class)->where('order', 1);
    }
}

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    /**
     * @var string
     */
    protected $table = 'animal_images';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'animal_id', 'image', 'order'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function animal()
    {
        return $this->belongsTo(Animal::class);
    }

    /**
     * @return string
     */
    public function getThumbnailAttribute()
    {
        return '<img class="thumb" src="' . $this->thumbUrl . '" alt="' . $this->animal->title . '">';
    }

    /**
     * @return string
     */
    public function getDisplayAttribute()
    {
        return '<img src="' . $this->url . '" alt="' . $this->animal->title . '">';
    }

    /**
     * @return string
     */
    public function getThumbUrlAttribute()
    {
        return '/img/animals/' . $this->animal->id . '/t_' . $this->image;
    }

    /**
     * @return string
     */
    public function getUrlAttribute()
    {
        return '/img/animals/' . $this->animal->id . '/' . $this->image;
    }
}

app/Http/Controllers/Admin/AnimalsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Requests\AnimalRequest;
use App\Services\AnimalService;
use File;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Intervention\Image\ImageManagerStatic as Image;

class AnimalsController extends Controller
{
    /**
     * @var AnimalService
     */
    protected $service;

    /**
     * AnimalsController constructor.
     * @param AnimalService $service
     */
    public function __construct(AnimalService $service)
    {
        $this->service = $service;
    }

    /**
     * Show the homepage.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $animals = $this->service->getAll();
        return view('admin.animals.index', compact('animals'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getUpdate($id)
    {
        if ($id == 'create') $animal = $this->service->model;
        else $animal = $this->service->get($id);
        return view('admin.animals.update', compact('animal'));
    }

    /**
     * @param $id
     * @param AnimalRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postUpdate($id, AnimalRequest $request)
    {
        if ($id == 'create') $entity = $this->service->create($request->all());
        else $entity = $this->service->update($this->service->get($id), $request->all());
        if ($entity) session()->flash('success', 'Success');
        else session()->flash('error', 'There was an error with your request');
        return redirect()->back();
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getImages($id)
    {
        if (!$animal = $this->service->get($id)) abort(404);
        return view('admin.animals.images', compact('animal'));
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postImages($id, Request $request)
    {
        if (!$animal = $this->service->get($id)) abort(404);
        if ($request->hasFile('files')) {
            foreach ($request->file('files') as $file) {
                try {
                    $path = public_path() . '/img/animals/' . $id . '/';
                    if (!file_exists($path)) {
                        mkdir($path, 666, true);
                    }

                    $name = rand(11111, 99999) . '.' . $file->getClientOriginalExtension();
                    $this->service->saveImage($animal, $name);
                    $image_resize = Image::make($file->getRealPath());
                    $image_resize->resize(800, 600);
                    $image_resize->save($path . $name);

                    $thumbnail = Image::make($file->getRealPath());
                    $thumbnail->resize(200, 150);
                    $thumbnail->save($path . 't_' . $name);
                } catch (FileNotFoundException $e) { }
            }
        }
        session()->flash('success', 'You have uploaded images.');
        return redirect()->back();
    }

    /**
     * @param Request $request
     * @return string
     */
    public function deleteImage(Request $request)
    {
        $image = $request->image;
        $name  = explode('/', $image)[4];
        $this->service->deleteImage($name);

        if(File::exists($image)) {
            File::delete($image);
        }

        return json_encode('success');
    }

    /**
     * @param Request $request
     */
    public function sortImages(Request $request)
    {
        $this->service->sortImages($request->order);
    }
}

app/Http/Controllers/AnimalController.php
<?php

namespace App\Http\Controllers;

use App\Services\AnimalService;

class AnimalController extends Controller
{
    /**
     * @var AnimalService
     */
    protected $service;

    /**
     * AnimalsController constructor.
     * @param AnimalService $service
     */
    public function __construct(AnimalService $service)
    {
        $this->service = $service;
    }

    /**
     * @param null $filter
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getListings($filter = null)
    {
        $listings = $this->service->getForSale($filter);
        $categories = $this->service->getCategories();
        return view('animals.index', compact('listings', 'categories', 'filter'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getAnimal($id)
    {
        if (!$animal = $this->service->get($id)) abort(404);
        if (!$animal->price || $animal->sold_for) abort(404);
        return view('animals.view', compact('animal'));
    }
}

resources/views/admin/animals/images.blade.php
@extends('layouts.interior')

@section('header')
    <style>
        section {
            position: relative;
            width: 800px;
            min-height: 500px;
            margin: 20px auto;
            border: 1px solid #444;
            border-radius: 4px;
            box-shadow: inset 0 0 6px rgba(0,0,0,0.2);
            background-color: #555;
        }

        form {
            position: absolute;
            z-index: 10;
            top: 10px;
            right: 10px;
        }

        #gallery {
            margin: 10px;
            padding: 0;
            overflow: hidden;
        }

        #gallery li {
            list-style: none;
            float: left;
        }

        #gallery li img {
            margin: 10px;
            background-color: #eee;
            box-shadow: 0 0 6px rgba(0,0,0,0.2);
        }

        #image-box {
            /* top: 50%;
             font-size: 35px;
             left: 50%;*/
            position: absolute;
            top: 45px;
            left: 90px;
            /*transform: translate(-50%, -50%);*/
        }

        #image-box img {
            border: 8px solid #777;
            background-color: #eee;
            box-shadow: 0 0 6px rgba(0,0,0,0.2);
        }

        .column-3 {
            width: 33.33%;
            text-align: center;
        }

        .thumb {
            cursor: pointer;
            width: 240px;
        }

        .largeImage {
            width: 600px;
            height: 400px;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <h1>Animals - {{ $animal->title }} Images</h1>
    </div>

    <p>
        This page will be a little gallery thing, I already have some basic js and styles. The idea being you click on a
        thumbnail and it will slow it in the side gallery and drag and drop to reorder. Let's work on this together.
    </p>

    <form action="" method="post" enctype="multipart/form-data">
        @csrf

        <label for="files">Upload Images Here</label>
        <input type="file" id="files" name="files[]" multiple>
        <button type="submit" class="btn">Upload</button>
    </form>

    <section>
        <div id="image-box">
            {!! $animal->featuredImage->display !!}
            <button class="delete">x</button>
        </div>
    </section>

    <section>
        <ul id="gallery">
            @foreach ($animal->images as $image)
                <li class="column-3" id="{{ $image->id }}">{!! $image->thumbnail !!}</li>
            @endforeach
        </ul>
    </section>

    @include('layouts.partials._admin_sidebar')
@endsection

@section('scripts')
    <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {
            $(".thumb").on('click', function(){
                var largeImage = $(this).attr("src");
                $("#image-box img").attr({src: largeImage});
            });

            $(".delete").on('click', function() {
                if (confirm("Are you sure you want to delete this image?") == true) {
                    deleteImage();
                }
            });

            function deleteImage() {
                var data = {
                    '_token': $('meta[name="csrf-token"]').attr('content'),
                    'image': $("#image-box img").attr("src")
                };

                $.ajax({
                    url: '/ajax/delete-image',
                    method: 'post',
                    data: data,
                    success: function(data) {
                        // remove image from the gallery
                    }
                });
            }

            $(function() {
                $("#gallery").sortable({
                    update: function (event, ui) {
                        var data = {
                            '_token': $('meta[name="csrf-token"]').attr('content'),
                            'order': $(this).sortable('toArray')
                        };

                        console.log(data);

                        $.ajax({
                            data: data,
                            type: 'post',
                            url: '/ajax/sort-images'
                        });
                    }
                });
                $("#gallery").disableSelection();
            });

            $(function() {
                $( "#image" ).resizable();
            });
        });
    </script>
@endsection

resources/views/admin/animals/index.blade.php
@extends('layouts.interior')

@section('content')
    <div class="container">
        <h1>Animals</h1>
    </div>

    <div>
        <a href="{{ route('admin.animals.update', ['id' => 'create']) }}" class="btn">Add Animal</a>
    </div>

    <table class="datatables">
        <thead>
        <tr>
            <th>Image</th>
            <th>Item #</th>
            <th>Title</th>
            <th>Price</th>
            <th>Status</th>
            <th>Options</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($animals as $animal)
                <tr>
                    <td></td>
                    <td>{{ $animal->item_number }}</td>
                    <td>{{ $animal->title }}</td>
                    <td>{{ $animal->price }}</td>
                    <td>{{ $animal->status }}</td>
                    <td>
                        <a href="{{ route('admin.animals.update', ['id' => $animal->id]) }}" class="button">Update</a>
                        <a href="{{ route('admin.animals.images', ['id' => $animal->id]) }}" class="button">Images</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @include('layouts.partials._admin_sidebar')
@endsection

resources/views/admin/animals/update.blade.php
@extends('layouts.interior')

@section('content')
    <div class="container">
        <h1>Animals - @if (isset($animal->id)) Update {{ $animal->title }} @else Create @endif</h1>
    </div>

    <form action="" method="post">
        @csrf

        <div class="flex vertical padded">
            <div>
                <label for="item_number" class="label">Item Number *</label>
                <input type="text" id="item_number" name="item_number" value="{{ old('item_number', $animal->item_number) }}" required>
            </div>

            <div>
                <label for="title" class="label">Title *</label>
                <input type="text" id="title" name="title" value="{{ old('title', $animal->title) }}" required>
            </div>

            <div>
                <label for="description" class="label">Description</label>
                <textarea id="description" name="description">{{ old('description', $animal->description) }}</textarea>
            </div>

            <div>
                <label for="categories" class="label">Categories *</label>
                <input type="text" id="categories" name="categories" value="{{ old('categories', $animal->categories) }}" required>
                <small>Separate with commas</small>
            </div>

            <div>
                <label for="species" class="label">Species *</label>
                <input type="text" id="species" name="species" value="{{ old('species', $animal->species) }}" required>
            </div>

            <div>
                <label for="gender" class="label">Gender *</label>
                <select name="gender" id="gender" required>
                    <option value="Unknown" @if (old('gender', $animal->gender) == 'Unknown') selected @endif>Unknown</option>
                    <option value="Male" @if (old('gender', $animal->gender) == 'Male') selected @endif>Male</option>
                    <option value="Female" @if (old('gender', $animal->gender) == 'Female') selected @endif>Female</option>
                </select>
            </div>

            <div>
                <label for="dob" class="label">Date of Birth</label>
                <input type="text" id="dob" name="dob" value="{{ old('dob', $animal->dob) }}">
            </div>

            <div>
                <label for="price" class="label">Price *</label>
                <input type="number" min="0" step="any" id="price" name="price" value="{{ old('price', $animal->price) }}" required>
            </div>

            <div>
                <label for="notes" class="label">Notes</label>
                <textarea id="notes" name="notes">{{ old('notes', $animal->notes) }}</textarea>
            </div>

            @if (isset($animal->id))
                <hr>
                <h3>Sale Info</h3>

                <div>
                    <label for="sold_to" class="label">Sold To</label>
                    <input type="text" id="sold_to" name="sold_to" value="{{ old('sold_to', $animal->sold_to) }}">
                </div>

                <div>
                    <label for="sold_at" class="label">Sold At</label>
                    <input type="date" id="sold_at" name="sold_at" value="{{ old('sold_at', $animal->sold_at) }}">
                </div>

                <div>
                    <label for="sold_for" class="label">Sold For</label>
                    <input type="number" min="0" step="any" id="sold_for" name="sold_for" value="{{ old('sold_for', $animal->sold_for) }}">
                </div>

                <div>
                    <label for="tracking_number" class="label">Tracking Number</label>
                    <input type="text" id="tracking_number" name="tracking_number" value="{{ old('tracking_number', $animal->tracking_number) }}">
                </div>

                <hr>
            @endif

            <div>
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </form>

    @include('layouts.partials._admin_sidebar')
@endsection